//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentmyhouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class banner
    {
        public int id { get; set; }
        public string strbannerblob { get; set; }
        public string strarea { get; set; }
        public Nullable<int> strtotal { get; set; }
    }
}
