//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentmyhouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class businessEngine
    {
        public int id { get; set; }
        public string strBusinessName { get; set; }
        public string strBusinessCaption { get; set; }
        public string strBusinessInformation { get; set; }
        public string strBusinessBanner { get; set; }
        public string strBusinessImage1 { get; set; }
        public string strBusinessLink { get; set; }
        public string strBusinessTelephone { get; set; }
        public string strBusinessEmail { get; set; }
        public string strBusinessUsername { get; set; }
        public Nullable<int> strBusinessUserID { get; set; }
        public Nullable<int> strApproved { get; set; }
        public Nullable<int> strInvisible { get; set; }
        public string strBusinessContact { get; set; }
        public Nullable<System.DateTime> strDate { get; set; }
        public Nullable<System.DateTime> strDateTime { get; set; }
        public string strBusinessCategory { get; set; }
        public string strBusinessOffer { get; set; }
        public string strBusinessFind { get; set; }
        public string strBusinessPostcode { get; set; }
        public Nullable<int> strBusinessFeature { get; set; }
        public Nullable<System.DateTime> strBusinessFeatureDate { get; set; }
        public Nullable<int> strBusinessSpotlight { get; set; }
        public Nullable<System.DateTime> strBusinessSpotlightDate { get; set; }
        public Nullable<System.DateTime> strBusinessSpotlightDateTimeBumpedUp { get; set; }
        public Nullable<System.DateTime> strdatetimebumpedup { get; set; }
        public string strBusinessAddress { get; set; }
        public string strBusinessSuburb { get; set; }
        public string strBusinessCity { get; set; }
        public string strBusinessCountry { get; set; }
        public string strIso { get; set; }
        public string strUserID { get; set; }
    }
}
