//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentmyhouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactTracking
    {
        public long id { get; set; }
        public string strSender { get; set; }
        public string strRecipient { get; set; }
        public string strsenderEmail { get; set; }
        public string strRecipientEmail { get; set; }
        public Nullable<System.DateTime> strDate { get; set; }
        public string strMessage { get; set; }
        public Nullable<int> strStatus { get; set; }
        public string strEvent { get; set; }
        public string strFromCountry { get; set; }
        public Nullable<System.DateTime> strDateTime { get; set; }
        public Nullable<int> strHouseId { get; set; }
        public Nullable<int> isHomeownerReply { get; set; }
        public string strFromISO { get; set; }
        public Nullable<int> ss_id { get; set; }
    }
}
