//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentmyhouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class file
    {
        public long id { get; set; }
        public string strImage1 { get; set; }
        public string strImage2 { get; set; }
        public string strImage3 { get; set; }
        public string strImage4 { get; set; }
        public string strImage5 { get; set; }
        public string strImage6 { get; set; }
    }
}
