//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentmyhouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class messagebox
    {
        public long id { get; set; }
        public string strFrom { get; set; }
        public string strTo { get; set; }
        public Nullable<System.DateTime> strDate { get; set; }
        public string strMessage { get; set; }
        public string strFromEmail { get; set; }
        public string strToEmail { get; set; }
        public Nullable<int> ss_id { get; set; }
    }
}
