//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentmyhouse.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class olympicsEntities : DbContext
    {
        public olympicsEntities()
            : base("name=olympicsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<banner> banners { get; set; }
        public DbSet<blacklist> blacklists { get; set; }
        public DbSet<businessEngine> businessEngines { get; set; }
        public DbSet<businessUser> businessUsers { get; set; }
        public DbSet<cm> cms { get; set; }
        public DbSet<contactTracking> contactTrackings { get; set; }
        public DbSet<eventtracking> eventtrackings { get; set; }
        public DbSet<favourite> favourites { get; set; }
        public DbSet<file> files { get; set; }
        public DbSet<googlemap> googlemaps { get; set; }
        public DbSet<messagebox> messageboxes { get; set; }
        public DbSet<promotion> promotions { get; set; }
        public DbSet<siteEvent> siteEvents { get; set; }
        public DbSet<sporteventstable> sporteventstables { get; set; }
        public DbSet<system> systems { get; set; }
        public DbSet<userprofile> userprofiles { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<usersdetail> usersdetails { get; set; }
    }
}
