//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentmyhouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class promotion
    {
        public long id { get; set; }
        public Nullable<bool> isSpotlight { get; set; }
        public Nullable<System.DateTime> spotlightDateTime { get; set; }
        public Nullable<System.DateTime> spotlightDateTimeBumpUp { get; set; }
        public Nullable<bool> isHighlight { get; set; }
        public Nullable<System.DateTime> highlightDateTime { get; set; }
        public Nullable<bool> isFeatured { get; set; }
        public Nullable<System.DateTime> featuredDateTime { get; set; }
        public Nullable<System.DateTime> featuredDateTimeBumpup { get; set; }
        public Nullable<bool> isUrgent { get; set; }
        public Nullable<System.DateTime> urgentDateTime { get; set; }
        public Nullable<int> houseid { get; set; }
        public Nullable<bool> islisting { get; set; }
        public Nullable<System.DateTime> listingDateTime { get; set; }
        public Nullable<System.DateTime> listingDateTimeBumpUp { get; set; }
        public Nullable<bool> isBumpup { get; set; }
        public Nullable<System.DateTime> bumpupDateTime { get; set; }
        public Nullable<int> ss_id { get; set; }
    }
}
