//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentmyhouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siteEvent
    {
        public long id { get; set; }
        public string strEvent { get; set; }
        public Nullable<System.DateTime> strDateTime { get; set; }
        public Nullable<int> strStatus { get; set; }
        public Nullable<int> ss_id { get; set; }
    }
}
