//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentmyhouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sporteventstable
    {
        public int id { get; set; }
        public string strtype { get; set; }
        public Nullable<int> strbed { get; set; }
        public string straddress { get; set; }
        public string strtown { get; set; }
        public string strcity { get; set; }
        public string strarea { get; set; }
        public string strcounty { get; set; }
        public string strpostcode { get; set; }
        public string strdescription { get; set; }
        public string strolympics { get; set; }
        public string strzone { get; set; }
        public string strname { get; set; }
        public string strphone { get; set; }
        public string stremail { get; set; }
        public string strimage1 { get; set; }
        public string strimage2 { get; set; }
        public string strapproved { get; set; }
        public Nullable<System.DateTime> strdate { get; set; }
        public Nullable<System.DateTime> strdatetime { get; set; }
        public string strpostedby { get; set; }
        public Nullable<int> strinvisible { get; set; }
        public Nullable<int> strhits { get; set; }
        public string stradtype { get; set; }
        public string strevent { get; set; }
        public string strprimevent { get; set; }
        public string strsecevent { get; set; }
        public string strswap { get; set; }
        public string strimage3 { get; set; }
        public string strimage4 { get; set; }
        public string strparking { get; set; }
        public string strPrice { get; set; }
        public string strDateFrom { get; set; }
        public string strDateTo { get; set; }
        public string strNeg { get; set; }
        public Nullable<System.DateTime> strEntered { get; set; }
        public Nullable<System.DateTime> strUpdated { get; set; }
        public Nullable<System.DateTime> strDateTimeBumpedUp { get; set; }
        public Nullable<System.DateTime> strSpotlightDateTime { get; set; }
        public Nullable<System.DateTime> strSpotlightDateTimeBumpedUp { get; set; }
        public string strEmailStatus { get; set; }
        public string strMeetHost { get; set; }
        public Nullable<int> ss_id { get; set; }
        public string strImage5 { get; set; }
        public string strImage6 { get; set; }
        public string strCaption { get; set; }
        public string strAdd1 { get; set; }
        public string strAdd2 { get; set; }
        public string strAdd3 { get; set; }
    }
}
