//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentmyhouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usersdetail
    {
        public long id { get; set; }
        public string username { get; set; }
        public string acquired { get; set; }
        public string ip { get; set; }
        public string browser { get; set; }
        public string region { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string ss_id { get; set; }
    }
}
