//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentmyhouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userprofile
    {
        public long id { get; set; }
        public string up_firstname { get; set; }
        public string up_lastname { get; set; }
        public string up_dob { get; set; }
        public string up_language { get; set; }
        public string up_aboutme { get; set; }
        public string up_image1 { get; set; }
        public string up_image2 { get; set; }
        public Nullable<System.DateTime> up_entered { get; set; }
        public Nullable<System.DateTime> up_updated { get; set; }
        public string up_username { get; set; }
        public Nullable<int> up_userid { get; set; }
        public string up_account { get; set; }
        public string up_status { get; set; }
        public Nullable<System.DateTime> up_date { get; set; }
        public Nullable<int> up_houseid { get; set; }
        public string up_work { get; set; }
        public string up_education { get; set; }
        public string up_hobbies { get; set; }
        public string up_gender { get; set; }
        public string up_country { get; set; }
        public string up_event { get; set; }
        public string up_contact { get; set; }
        public string up_type { get; set; }
        public string up_swap { get; set; }
        public string up_membersince { get; set; }
        public string up_iso { get; set; }
        public string up_bed { get; set; }
        public Nullable<int> ss_id { get; set; }
        public string strHome { get; set; }
        public string up_caption { get; set; }
        public string up_datefrom { get; set; }
        public string up_dateto { get; set; }
    }
}
