//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentmyhouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public string strusername { get; set; }
        public string strpassword { get; set; }
        public Nullable<int> strsecurity { get; set; }
        public string strkeyword { get; set; }
        public Nullable<System.DateTime> strdate { get; set; }
        public string strstatus { get; set; }
        public Nullable<System.DateTime> strlast { get; set; }
        public string strCountry { get; set; }
        public string strIso { get; set; }
        public string fb_userid { get; set; }
        public string blacklist { get; set; }
        public string strEmailStatus { get; set; }
        public string strUnsubscribe { get; set; }
        public Nullable<int> ss_id { get; set; }
        public string strTerms { get; set; }
        public string strFirstname { get; set; }
        public string strLastname { get; set; }
    }
}
